# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NFLoop_Widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(498, 353)
        self.EEGThrIncrement = QtWidgets.QLineEdit(Form)
        self.EEGThrIncrement.setGeometry(QtCore.QRect(150, 160, 31, 23))
        self.EEGThrIncrement.setObjectName("EEGThrIncrement")
        self.EEGThr = QtWidgets.QLineEdit(Form)
        self.EEGThr.setGeometry(QtCore.QRect(120, 130, 91, 23))
        self.EEGThr.setObjectName("EEGThr")
        self.HideSignals = QtWidgets.QPushButton(Form)
        self.HideSignals.setGeometry(QtCore.QRect(390, 220, 91, 23))
        self.HideSignals.setObjectName("HideSignals")
        self.EEGIncrementDown = QtWidgets.QPushButton(Form)
        self.EEGIncrementDown.setGeometry(QtCore.QRect(120, 160, 21, 23))
        self.EEGIncrementDown.setObjectName("EEGIncrementDown")
        self.EMGStScaling = QtWidgets.QLineEdit(Form)
        self.EMGStScaling.setGeometry(QtCore.QRect(250, 250, 71, 23))
        self.EMGStScaling.setObjectName("EMGStScaling")
        self.Time = QtWidgets.QLabel(Form)
        self.Time.setGeometry(QtCore.QRect(180, 41, 59, 15))
        self.Time.setObjectName("Time")
        self.EMGIncrementUp = QtWidgets.QPushButton(Form)
        self.EMGIncrementUp.setGeometry(QtCore.QRect(310, 160, 21, 23))
        self.EMGIncrementUp.setObjectName("EMGIncrementUp")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 351, 20))
        self.label_7.setObjectName("label_7")
        self.EEGStScaling = QtWidgets.QLineEdit(Form)
        self.EEGStScaling.setGeometry(QtCore.QRect(130, 250, 71, 23))
        self.EEGStScaling.setObjectName("EEGStScaling")
        self.TimeRunning = QtWidgets.QLabel(Form)
        self.TimeRunning.setGeometry(QtCore.QRect(80, 40, 111, 16))
        self.TimeRunning.setObjectName("TimeRunning")
        self.ShowSignals = QtWidgets.QPushButton(Form)
        self.ShowSignals.setGeometry(QtCore.QRect(390, 190, 91, 23))
        self.ShowSignals.setObjectName("ShowSignals")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 101, 16))
        self.label_3.setObjectName("label_3")
        self.EEGUOffset = QtWidgets.QLineEdit(Form)
        self.EEGUOffset.setGeometry(QtCore.QRect(170, 290, 31, 23))
        self.EEGUOffset.setObjectName("EEGUOffset")
        self.EMGThr = QtWidgets.QLineEdit(Form)
        self.EMGThr.setGeometry(QtCore.QRect(240, 130, 91, 23))
        self.EMGThr.setObjectName("EMGThr")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(270, 100, 59, 15))
        self.label_5.setObjectName("label_5")
        self.EEGstLOffset = QtWidgets.QLineEdit(Form)
        self.EEGstLOffset.setGeometry(QtCore.QRect(130, 290, 31, 23))
        self.EEGstLOffset.setObjectName("EEGstLOffset")
        self.EEGIncrementUp = QtWidgets.QPushButton(Form)
        self.EEGIncrementUp.setGeometry(QtCore.QRect(190, 160, 21, 23))
        self.EEGIncrementUp.setObjectName("EEGIncrementUp")
        self.EMGIncrementDown = QtWidgets.QPushButton(Form)
        self.EMGIncrementDown.setGeometry(QtCore.QRect(240, 160, 21, 23))
        self.EMGIncrementDown.setObjectName("EMGIncrementDown")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 100, 59, 15))
        self.label.setObjectName("label")
        self.StartCamera = QtWidgets.QPushButton(Form)
        self.StartCamera.setGeometry(QtCore.QRect(390, 110, 91, 23))
        self.StartCamera.setObjectName("StartCamera")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(390, 80, 101, 20))
        self.label_6.setObjectName("label_6")
        self.EMGThrIncrement = QtWidgets.QLineEdit(Form)
        self.EMGThrIncrement.setGeometry(QtCore.QRect(270, 160, 31, 23))
        self.EMGThrIncrement.setObjectName("EMGThrIncrement")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(19, 131, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 292, 91, 16))
        self.label_4.setObjectName("label_4")
        self.EMGLOffset = QtWidgets.QLineEdit(Form)
        self.EMGLOffset.setGeometry(QtCore.QRect(250, 290, 31, 23))
        self.EMGLOffset.setObjectName("EMGLOffset")
        self.StopCamera = QtWidgets.QPushButton(Form)
        self.StopCamera.setGeometry(QtCore.QRect(390, 140, 91, 23))
        self.StopCamera.setObjectName("StopCamera")
        self.StopLoop = QtWidgets.QPushButton(Form)
        self.StopLoop.setGeometry(QtCore.QRect(390, 38, 91, 23))
        self.StopLoop.setObjectName("StopLoop")
        self.EMGUOffset = QtWidgets.QLineEdit(Form)
        self.EMGUOffset.setGeometry(QtCore.QRect(290, 290, 31, 23))
        self.EMGUOffset.setObjectName("EMGUOffset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.HideSignals.setText(_translate("Form", "Hide Signals"))
        self.EEGIncrementDown.setText(_translate("Form", "PushButton"))
        self.Time.setText(_translate("Form", "00:00"))
        self.EMGIncrementUp.setText(_translate("Form", "PushButton"))
        self.label_7.setText(_translate("Form", "Scaling/Offset Options for Display on Stimulus Computer"))
        self.TimeRunning.setText(_translate("Form", "Loop Running:"))
        self.ShowSignals.setText(_translate("Form", "Show Signals"))
        self.label_3.setText(_translate("Form", "St Scaling (uV)"))
        self.label_5.setText(_translate("Form", "EMG"))
        self.EEGIncrementUp.setText(_translate("Form", "PushButton"))
        self.EMGIncrementDown.setText(_translate("Form", "PushButton"))
        self.label.setText(_translate("Form", "EEG"))
        self.StartCamera.setText(_translate("Form", "Start Camera"))
        self.label_6.setText(_translate("Form", "Control Options"))
        self.label_2.setText(_translate("Form", "Threshold (uV)"))
        self.label_4.setText(_translate("Form", "St Offsets (%)"))
        self.StopCamera.setText(_translate("Form", "Stop Camera"))
        self.StopLoop.setText(_translate("Form", "Stop Loop"))


